twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        locales: '%app.locales%'
        option_service: '@App\Controller\Services\OptionsService'
        exercice_en_cours: '@App\Controller\Services\AdministrationService'
when@test:
    twig:
        strict_variables: true
