vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        docs_operateurs:
            uri_prefix: /images/doc_operateurs
            upload_destination: '%kernel.project_dir%/public/images/doc_operateurs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
